export const lightgray = "#a7a8ac"
export const orange = "#fd8050"
export const white = "#fdfdfe"
export const green = "#00aa86"
export const greenGrey = "#bee1d3"
export const blueGrey = "#388389"
export const blue = "#1ab7ce"
export const charcoal = "#303030"
export const yellow = "#FFF200"

export const styleThemes = {
	blueGrey: {
		backgroundColor: blueGrey,
		color: white,
		textShadow: `2px 2px ${charcoal}`,
		finalColor: orange,
		finalColorShadow: `3px 3px ${blue}`,
		gameTypeColor: yellow,
		teamNameBannerBG: orange,
		teamNameBannerColor: white,
		teamNameBannerShadow: `2px 2px ${charcoal}`,
		scoreColor: white,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `2px 2px ${charcoal}`,
	},
	blue: {
		backgroundColor: blue,
		color: white,
		textShadow: `2px 2px ${charcoal}`,
		finalColor: yellow,
		finalColorShadow: `3px 3px ${orange}`,
		gameTypeColor: orange,
		teamNameBannerBG: white,
		teamNameBannerColor: orange,
		teamNameBannerShadow: `1px px ${charcoal}`,
		scoreColor: orange,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `2px 2px ${charcoal}`,
	},
	charcoal: {
		backgroundColor: charcoal,
		color: orange,
		textShadow: `2px 2px ${green}`,
		finalColor: green,
		finalColorShadow: `3px 3px ${yellow}`,
		gameTypeColor: yellow,
		teamNameBannerBG: orange,
		teamNameBannerColor: white,
		teamNameBannerShadow: `2px 2px ${charcoal}`,
		scoreColor: white,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `2px 2px ${charcoal}`,
	},
	green: {
		backgroundColor: green,
		color: white,
		textShadow: `2px 2px ${charcoal}`,
		finalColor: yellow,
		finalColorShadow: `3px 3px ${charcoal}`,
		gameTypeColor: yellow,
		teamNameBannerBG: orange,
		teamNameBannerColor: white,
		teamNameBannerShadow: `2px 2px ${charcoal}`,
		scoreColor: white,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `-1px -1px 0 ${white}, 1px -1px 0 ${white}, -1px 1px 0 ${white}, 1px 1px 0 ${white};`,
	},
	greenGrey: {
		backgroundColor: greenGrey,
		color: white,
		textShadow: `2px 2px ${green}`,
		finalColor: yellow,
		finalColorShadow: `3px 3px ${charcoal}`,
		gameTypeColor: "#00aa86",
		teamNameBannerBG: green,
		teamNameBannerColor: white,
		teamNameBannerShadow: `2px 2px ${charcoal}`,
		scoreColor: white,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `2px 2px ${charcoal}`,
	},
	lightgrey: {
		backgroundColor: lightgray,
		color: white,
		textShadow: `2px 2px ${charcoal}`,
		finalColor: green,
		finalColorShadow: `3px 3px ${yellow}`,
		gameTypeColor: green,
		teamNameBannerBG: green,
		teamNameBannerColor: white,
		teamNameBannerShadow: `0px 0px ${orange}`,
		scoreColor: white,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `0px 0px ${orange}`,
	},
	orange: {
		backgroundColor: orange,
		color: white,
		textShadow: `2px 2px ${charcoal}`,
		finalColor: green,
		finalColorShadow: `3px 3px ${charcoal}`,
		gameTypeColor: green,
		teamNameBannerBG: green,
		teamNameBannerColor: white,
		teamNameBannerShadow: `2px 2px ${charcoal}`,
		scoreColor: white,
		WebkitTextStrokeColor: charcoal,
		scoreColorShadow: `2px 2px ${charcoal}`,
	},

	white: {
		backgroundColor: white,
		color: green,
		textShadow: `2px 2px ${charcoal}`,
		finalColor: orange,
		finalColorShadow: `3px 3px ${charcoal}`,
		gameTypeColor: charcoal,
		teamNameBannerBG: charcoal,
		teamNameBannerColor: white,
		teamNameBannerShadow: `2px 2px ${charcoal}`,
		scoreColor: white,
		WebkitTextStrokeColor: orange,
		scoreColorShadow: `2px 2px ${charcoal}`,
	},

	// Add more themes as needed
}
